### ISSUE TITLE
Project log book.

### ISSUE THREAD

**Issue by niroshubey966** [niroshubey966/deepstreamIO#2]
I think in this project. We did lot of works behind the github. But they were not write down in any ware. So at the last we can't prove our works that we did behind of the github.

And also I think this log can be used to describe our tasks like why we do that, for what, what are the advantages etc.

So I propose to make a project **Log book** to do that. 

What do you think?

**Comment by melani08** [comment]
yeah that's true...it will useful to us

**Comment by niroshubey966** [comment]
Thanks **melani08** for your reply. OK I will open a new file for the project log book. We write down hear all tasks that we did in this project. Specially we write down hear that we are done behind the github.

who can contribute to success this, I will be appreciated.
